version: '3'

services:
  rtpengine:
    build: .
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - /etc/rtpengine/rtpengine.conf:/etc/rtpengine/rtpengine.conf:ro
      - /var/log/rtpengine:/var/log/rtpengine
      - /var/spool/rtpengine:/var/spool/rtpengine
    command: ["--config-file=/etc/rtpengine/rtpengine.conf", "--foreground"]