apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    # Let's Encrypt Production server
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@ringer.tel  # Change to your email
    privateKeySecretRef:
      name: letsencrypt-production-key
    solvers:
    # HTTP-01 challenge for standard domains
    - http01:
        ingress:
          ingressClassName: nginx
      selector:
        dnsNames:
        - 'api-v2.ringer.tel'
        - 'api.ringer.net'
        - 'grafana.ringer.tel'
        - 'prometheus.ringer.tel'
        - 'homer.ringer.tel'
    # DNS-01 challenge for wildcard certificates using Gandi
    - dns01:
        webhook:
          groupName: acme.bwolf.me
          solverName: gandi
          config:
            apiKeySecretRef:
              name: gandi-api-token
              key: api-token
      selector:
        dnsNames:
        - '*.ringer.tel'
        - '*.ringer.net'
        - '*.sip.ringer.tel'
        - '*.sip.ringer.net'